"""Add user data persistence with caching and multi-methodology support

Revision ID: 3130c5b24b3a
Revises: 004_add_owner_name
Create Date: 2025-11-23 18:42:02.605102

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '3130c5b24b3a'
down_revision = '004_add_owner_name'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###

    # Add new columns to existing tables
    op.add_column('birth_charts', sa.Column('methodology', sa.String(length=50), server_default='parashara', nullable=False))
    op.add_column('birth_charts', sa.Column('chart_name', sa.String(length=255), nullable=True))
    op.create_index(op.f('ix_birth_charts_methodology'), 'birth_charts', ['methodology'], unique=False)

    # Create subscriptions table
    op.create_table(
        'subscriptions',
        sa.Column('id', sa.String(length=36), nullable=False),
        sa.Column('created_at', sa.DateTime(), nullable=False),
        sa.Column('updated_at', sa.DateTime(), nullable=False),
        sa.Column('is_active', sa.Boolean(), nullable=False),
        sa.Column('user_id', sa.String(length=36), nullable=False),
        sa.Column('tier', sa.Enum('free', 'standard', 'premium', 'professional', 'enterprise', name='subscriptiontier', native_enum=False), nullable=False),
        sa.Column('status', sa.Enum('active', 'cancelled', 'expired', 'trial', 'suspended', name='subscriptionstatus', native_enum=False), nullable=False),
        sa.Column('price_per_month', sa.Float(), nullable=False),
        sa.Column('currency', sa.String(length=3), nullable=False),
        sa.Column('start_date', sa.DateTime(), nullable=False),
        sa.Column('end_date', sa.DateTime(), nullable=True),
        sa.Column('trial_end_date', sa.DateTime(), nullable=True),
        sa.Column('next_billing_date', sa.DateTime(), nullable=True),
        sa.Column('payment_method', sa.String(length=50), nullable=True),
        sa.Column('payment_id', sa.String(length=255), nullable=True),
        sa.Column('max_charts_per_month', sa.Integer(), nullable=False),
        sa.Column('max_saved_charts', sa.Integer(), nullable=False),
        sa.Column('max_ai_queries_per_month', sa.Integer(), nullable=False),
        sa.Column('max_export_per_month', sa.Integer(), nullable=False),
        sa.Column('charts_used_this_month', sa.Integer(), nullable=False),
        sa.Column('ai_queries_used_this_month', sa.Integer(), nullable=False),
        sa.Column('exports_used_this_month', sa.Integer(), nullable=False),
        sa.Column('usage_reset_date', sa.DateTime(), nullable=False),
        sa.Column('enable_ai', sa.Boolean(), nullable=False),
        sa.Column('enable_advanced_charts', sa.Boolean(), nullable=False),
        sa.Column('enable_api_access', sa.Boolean(), nullable=False),
        sa.Column('enable_priority_support', sa.Boolean(), nullable=False),
        sa.Column('notes', sa.Text(), nullable=True),
        sa.Column('cancellation_reason', sa.Text(), nullable=True),
        sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_subscriptions_created_at'), 'subscriptions', ['created_at'], unique=False)
    op.create_index(op.f('ix_subscriptions_is_active'), 'subscriptions', ['is_active'], unique=False)
    op.create_index(op.f('ix_subscriptions_status'), 'subscriptions', ['status'], unique=False)
    op.create_index(op.f('ix_subscriptions_tier'), 'subscriptions', ['tier'], unique=False)
    op.create_index(op.f('ix_subscriptions_updated_at'), 'subscriptions', ['updated_at'], unique=False)
    op.create_index(op.f('ix_subscriptions_user_id'), 'subscriptions', ['user_id'], unique=True)

    # Create chart_cache table
    op.create_table(
        'chart_cache',
        sa.Column('id', sa.String(length=36), nullable=False),
        sa.Column('created_at', sa.DateTime(), nullable=False),
        sa.Column('updated_at', sa.DateTime(), nullable=False),
        sa.Column('is_active', sa.Boolean(), nullable=False),
        sa.Column('birth_chart_id', sa.String(length=36), nullable=False),
        sa.Column('cache_type', sa.Enum('natal_positions', 'natal_houses', 'natal_divisional', 'natal_dasha_balance', 'natal_yogas', 'natal_shadbala', 'natal_ashtakavarga', 'current_transits', 'current_dasha', 'compatibility', 'prashna', 'muhurta', name='cachetype', native_enum=False), nullable=False),
        sa.Column('cache_key', sa.String(length=255), nullable=False),
        sa.Column('cache_data', sa.JSON(), nullable=False),
        sa.Column('expires_at', sa.DateTime(), nullable=True),
        sa.Column('is_permanent', sa.Boolean(), nullable=False),
        sa.Column('calculation_time_ms', sa.Integer(), nullable=True),
        sa.Column('calculation_params', sa.JSON(), nullable=True),
        sa.Column('cache_version', sa.String(length=20), nullable=False),
        sa.ForeignKeyConstraint(['birth_chart_id'], ['birth_charts.id'], ),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_chart_cache_birth_chart_id'), 'chart_cache', ['birth_chart_id'], unique=False)
    op.create_index(op.f('ix_chart_cache_cache_key'), 'chart_cache', ['cache_key'], unique=False)
    op.create_index(op.f('ix_chart_cache_cache_type'), 'chart_cache', ['cache_type'], unique=False)
    op.create_index(op.f('ix_chart_cache_created_at'), 'chart_cache', ['created_at'], unique=False)
    op.create_index(op.f('ix_chart_cache_expires_at'), 'chart_cache', ['expires_at'], unique=False)
    op.create_index(op.f('ix_chart_cache_is_active'), 'chart_cache', ['is_active'], unique=False)
    op.create_index(op.f('ix_chart_cache_is_permanent'), 'chart_cache', ['is_permanent'], unique=False)
    op.create_index(op.f('ix_chart_cache_updated_at'), 'chart_cache', ['updated_at'], unique=False)
    op.create_index('idx_chart_cache_lookup', 'chart_cache', ['birth_chart_id', 'cache_type', 'cache_key'], unique=False)
    op.create_index('idx_cache_expiry', 'chart_cache', ['expires_at', 'is_permanent'], unique=False)

    # Create user_requests table
    op.create_table(
        'user_requests',
        sa.Column('id', sa.String(length=36), nullable=False),
        sa.Column('created_at', sa.DateTime(), nullable=False),
        sa.Column('updated_at', sa.DateTime(), nullable=False),
        sa.Column('is_active', sa.Boolean(), nullable=False),
        sa.Column('user_id', sa.String(length=36), nullable=False),
        sa.Column('birth_chart_id', sa.String(length=36), nullable=True),
        sa.Column('request_type', sa.String(length=50), nullable=False),
        sa.Column('request_endpoint', sa.String(length=255), nullable=True),
        sa.Column('request_method', sa.String(length=10), nullable=True),
        sa.Column('request_params', sa.JSON(), nullable=True),
        sa.Column('response_status', sa.Integer(), nullable=True),
        sa.Column('response_time_ms', sa.Integer(), nullable=True),
        sa.Column('ai_query', sa.Text(), nullable=True),
        sa.Column('ai_response', sa.Text(), nullable=True),
        sa.Column('ai_model', sa.String(length=50), nullable=True),
        sa.Column('ai_tokens_used', sa.Integer(), nullable=True),
        sa.Column('export_format', sa.String(length=20), nullable=True),
        sa.Column('export_file_size', sa.Integer(), nullable=True),
        sa.Column('error_message', sa.Text(), nullable=True),
        sa.ForeignKeyConstraint(['birth_chart_id'], ['birth_charts.id'], ),
        sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_requests_birth_chart_id'), 'user_requests', ['birth_chart_id'], unique=False)
    op.create_index(op.f('ix_user_requests_created_at'), 'user_requests', ['created_at'], unique=False)
    op.create_index(op.f('ix_user_requests_is_active'), 'user_requests', ['is_active'], unique=False)
    op.create_index(op.f('ix_user_requests_request_type'), 'user_requests', ['request_type'], unique=False)
    op.create_index(op.f('ix_user_requests_updated_at'), 'user_requests', ['updated_at'], unique=False)
    op.create_index(op.f('ix_user_requests_user_id'), 'user_requests', ['user_id'], unique=False)
    op.alter_column('llm_admin_defaults', 'default_provider',
               existing_type=mysql.ENUM('OPENAI', 'AZURE_OPENAI', 'ANTHROPIC', 'GOOGLE', 'OPENROUTER', 'MISTRAL', 'TOGETHER', 'GROQ', 'PERPLEXITY', 'COHERE', 'XAI', 'OLLAMA', 'CUSTOM', collation='utf8mb4_unicode_ci'),
               type_=sa.Enum('openai', 'azure-openai', 'anthropic', 'google', 'openrouter', 'mistral', 'together', 'groq', 'perplexity', 'cohere', 'xai', 'ollama', 'custom', name='llmprovider', native_enum=False),
               existing_nullable=True)
    op.alter_column('llm_audit_logs', 'provider',
               existing_type=mysql.ENUM('OPENAI', 'AZURE_OPENAI', 'ANTHROPIC', 'GOOGLE', 'OPENROUTER', 'MISTRAL', 'TOGETHER', 'GROQ', 'PERPLEXITY', 'COHERE', 'XAI', 'OLLAMA', 'CUSTOM', collation='utf8mb4_unicode_ci'),
               type_=sa.Enum('openai', 'azure-openai', 'anthropic', 'google', 'openrouter', 'mistral', 'together', 'groq', 'perplexity', 'cohere', 'xai', 'ollama', 'custom', name='llmprovider', native_enum=False),
               existing_nullable=True)
    op.alter_column('llm_configs', 'provider',
               existing_type=mysql.ENUM('openai', 'azure-openai', 'anthropic', 'google', 'openrouter', 'mistral', 'together', 'groq', 'perplexity', 'cohere', 'xai', 'ollama', 'custom', collation='utf8mb4_unicode_ci'),
               type_=sa.Enum('openai', 'azure-openai', 'anthropic', 'google', 'openrouter', 'mistral', 'together', 'groq', 'perplexity', 'cohere', 'xai', 'ollama', 'custom', name='llmprovider', native_enum=False),
               existing_nullable=True)
    op.add_column('llm_shared_key_usage', sa.Column('is_active', sa.Boolean(), nullable=False))
    op.create_index(op.f('ix_llm_shared_key_usage_created_at'), 'llm_shared_key_usage', ['created_at'], unique=False)
    op.create_index(op.f('ix_llm_shared_key_usage_is_active'), 'llm_shared_key_usage', ['is_active'], unique=False)
    op.create_index(op.f('ix_llm_shared_key_usage_updated_at'), 'llm_shared_key_usage', ['updated_at'], unique=False)
    op.alter_column('llm_shared_keys', 'provider',
               existing_type=mysql.ENUM('openai', 'azure-openai', 'anthropic', 'google', 'openrouter', 'mistral', 'together', 'groq', 'perplexity', 'cohere', 'xai', 'ollama', 'custom', collation='utf8mb4_unicode_ci'),
               type_=sa.Enum('openai', 'azure-openai', 'anthropic', 'google', 'openrouter', 'mistral', 'together', 'groq', 'perplexity', 'cohere', 'xai', 'ollama', 'custom', name='llmprovider', native_enum=False),
               existing_nullable=False)
    op.create_index(op.f('ix_llm_shared_keys_created_at'), 'llm_shared_keys', ['created_at'], unique=False)
    op.create_index(op.f('ix_llm_shared_keys_updated_at'), 'llm_shared_keys', ['updated_at'], unique=False)
    op.add_column('users', sa.Column('default_ayanamsha', sa.String(length=50), nullable=False))
    op.add_column('users', sa.Column('default_house_system', sa.String(length=50), nullable=False))
    op.add_column('users', sa.Column('default_chart_style', sa.String(length=50), nullable=False))
    op.add_column('users', sa.Column('preferred_methodology', sa.String(length=50), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###

    # Drop new tables
    op.drop_index(op.f('ix_user_requests_user_id'), table_name='user_requests')
    op.drop_index(op.f('ix_user_requests_updated_at'), table_name='user_requests')
    op.drop_index(op.f('ix_user_requests_request_type'), table_name='user_requests')
    op.drop_index(op.f('ix_user_requests_is_active'), table_name='user_requests')
    op.drop_index(op.f('ix_user_requests_created_at'), table_name='user_requests')
    op.drop_index(op.f('ix_user_requests_birth_chart_id'), table_name='user_requests')
    op.drop_table('user_requests')

    op.drop_index('idx_cache_expiry', table_name='chart_cache')
    op.drop_index('idx_chart_cache_lookup', table_name='chart_cache')
    op.drop_index(op.f('ix_chart_cache_updated_at'), table_name='chart_cache')
    op.drop_index(op.f('ix_chart_cache_is_permanent'), table_name='chart_cache')
    op.drop_index(op.f('ix_chart_cache_is_active'), table_name='chart_cache')
    op.drop_index(op.f('ix_chart_cache_expires_at'), table_name='chart_cache')
    op.drop_index(op.f('ix_chart_cache_created_at'), table_name='chart_cache')
    op.drop_index(op.f('ix_chart_cache_cache_type'), table_name='chart_cache')
    op.drop_index(op.f('ix_chart_cache_cache_key'), table_name='chart_cache')
    op.drop_index(op.f('ix_chart_cache_birth_chart_id'), table_name='chart_cache')
    op.drop_table('chart_cache')

    op.drop_index(op.f('ix_subscriptions_user_id'), table_name='subscriptions')
    op.drop_index(op.f('ix_subscriptions_updated_at'), table_name='subscriptions')
    op.drop_index(op.f('ix_subscriptions_tier'), table_name='subscriptions')
    op.drop_index(op.f('ix_subscriptions_status'), table_name='subscriptions')
    op.drop_index(op.f('ix_subscriptions_is_active'), table_name='subscriptions')
    op.drop_index(op.f('ix_subscriptions_created_at'), table_name='subscriptions')
    op.drop_table('subscriptions')

    # Drop columns from existing tables
    op.drop_column('users', 'preferred_methodology')
    op.drop_column('users', 'default_chart_style')
    op.drop_column('users', 'default_house_system')
    op.drop_column('users', 'default_ayanamsha')
    op.drop_index(op.f('ix_llm_shared_keys_updated_at'), table_name='llm_shared_keys')
    op.drop_index(op.f('ix_llm_shared_keys_created_at'), table_name='llm_shared_keys')
    op.alter_column('llm_shared_keys', 'provider',
               existing_type=sa.Enum('openai', 'azure-openai', 'anthropic', 'google', 'openrouter', 'mistral', 'together', 'groq', 'perplexity', 'cohere', 'xai', 'ollama', 'custom', name='llmprovider', native_enum=False),
               type_=mysql.ENUM('openai', 'azure-openai', 'anthropic', 'google', 'openrouter', 'mistral', 'together', 'groq', 'perplexity', 'cohere', 'xai', 'ollama', 'custom', collation='utf8mb4_unicode_ci'),
               existing_nullable=False)
    op.drop_index(op.f('ix_llm_shared_key_usage_updated_at'), table_name='llm_shared_key_usage')
    op.drop_index(op.f('ix_llm_shared_key_usage_is_active'), table_name='llm_shared_key_usage')
    op.drop_index(op.f('ix_llm_shared_key_usage_created_at'), table_name='llm_shared_key_usage')
    op.drop_column('llm_shared_key_usage', 'is_active')
    op.alter_column('llm_configs', 'provider',
               existing_type=sa.Enum('openai', 'azure-openai', 'anthropic', 'google', 'openrouter', 'mistral', 'together', 'groq', 'perplexity', 'cohere', 'xai', 'ollama', 'custom', name='llmprovider', native_enum=False),
               type_=mysql.ENUM('openai', 'azure-openai', 'anthropic', 'google', 'openrouter', 'mistral', 'together', 'groq', 'perplexity', 'cohere', 'xai', 'ollama', 'custom', collation='utf8mb4_unicode_ci'),
               existing_nullable=True)
    op.alter_column('llm_audit_logs', 'provider',
               existing_type=sa.Enum('openai', 'azure-openai', 'anthropic', 'google', 'openrouter', 'mistral', 'together', 'groq', 'perplexity', 'cohere', 'xai', 'ollama', 'custom', name='llmprovider', native_enum=False),
               type_=mysql.ENUM('OPENAI', 'AZURE_OPENAI', 'ANTHROPIC', 'GOOGLE', 'OPENROUTER', 'MISTRAL', 'TOGETHER', 'GROQ', 'PERPLEXITY', 'COHERE', 'XAI', 'OLLAMA', 'CUSTOM', collation='utf8mb4_unicode_ci'),
               existing_nullable=True)
    op.alter_column('llm_admin_defaults', 'default_provider',
               existing_type=sa.Enum('openai', 'azure-openai', 'anthropic', 'google', 'openrouter', 'mistral', 'together', 'groq', 'perplexity', 'cohere', 'xai', 'ollama', 'custom', name='llmprovider', native_enum=False),
               type_=mysql.ENUM('OPENAI', 'AZURE_OPENAI', 'ANTHROPIC', 'GOOGLE', 'OPENROUTER', 'MISTRAL', 'TOGETHER', 'GROQ', 'PERPLEXITY', 'COHERE', 'XAI', 'OLLAMA', 'CUSTOM', collation='utf8mb4_unicode_ci'),
               existing_nullable=True)
    op.drop_index(op.f('ix_birth_charts_methodology'), table_name='birth_charts')
    op.drop_column('birth_charts', 'chart_name')
    op.drop_column('birth_charts', 'methodology')
    # ### end Alembic commands ###

