/**
 * HTML Report Viewer Component
 *
 * Displays a complete standalone HTML Vedic horoscope report
 * Generated by AI with comprehensive analysis and traditional styling
 */

import React, { useRef, useState } from 'react';
import { Download, ExternalLink, Printer } from 'lucide-react';
import { Button } from '@/components/ui/button';
import DOMPurify from 'isomorphic-dompurify';

interface HtmlReportViewerProps {
  htmlContent: string;
  personName?: string;
  onClose?: () => void;
}

export const HtmlReportViewer: React.FC<HtmlReportViewerProps> = ({
  htmlContent,
  personName = 'User',
  onClose
}) => {
  const iframeRef = useRef<HTMLIFrameElement>(null);
  const [isDownloading, setIsDownloading] = useState(false);

  // Sanitize HTML to prevent XSS attacks
  const sanitizedHtml = DOMPurify.sanitize(htmlContent, {
    ADD_TAGS: ['style', 'link'],
    ADD_ATTR: ['target', 'rel'],
    ALLOW_UNKNOWN_PROTOCOLS: false
  });

  const handleDownloadHtml = () => {
    try {
      setIsDownloading(true);

      // Create a blob from the HTML content
      const blob = new Blob([htmlContent], { type: 'text/html;charset=utf-8' });

      // Create download link
      const url = URL.createObjectURL(blob);
      const link = document.createElement('a');
      link.href = url;

      // Generate filename
      const timestamp = new Date().toISOString().split('T')[0];
      const filename = `Vedic_Horoscope_${personName.replace(/\s+/g, '_')}_${timestamp}.html`;
      link.download = filename;

      // Trigger download
      document.body.appendChild(link);
      link.click();
      document.body.removeChild(link);

      // Clean up
      URL.revokeObjectURL(url);
    } catch (error) {
      console.error('Error downloading HTML:', error);
      alert('Failed to download HTML file. Please try again.');
    } finally {
      setIsDownloading(false);
    }
  };

  const handlePrint = () => {
    if (iframeRef.current && iframeRef.current.contentWindow) {
      try {
        iframeRef.current.contentWindow.print();
      } catch (error) {
        console.error('Error printing:', error);
        // Fallback: open in new window and print
        const printWindow = window.open('', '_blank');
        if (printWindow) {
          printWindow.document.write(htmlContent);
          printWindow.document.close();
          printWindow.print();
        }
      }
    }
  };

  const handleOpenInNewTab = () => {
    const newWindow = window.open('', '_blank');
    if (newWindow) {
      newWindow.document.write(htmlContent);
      newWindow.document.close();
    }
  };

  return (
    <div className="html-report-viewer-container">
      {/* Toolbar */}
      <div className="toolbar">
        <div className="toolbar-actions">
          <Button
            onClick={handleDownloadHtml}
            disabled={isDownloading}
            variant="outline"
            size="sm"
          >
            {isDownloading ? (
              <>
                <Download className="h-4 w-4 mr-2 animate-pulse" />
                Downloading...
              </>
            ) : (
              <>
                <Download className="h-4 w-4 mr-2" />
                Download HTML
              </>
            )}
          </Button>

          <Button
            onClick={handlePrint}
            variant="outline"
            size="sm"
          >
            <Printer className="h-4 w-4 mr-2" />
            Print
          </Button>

          <Button
            onClick={handleOpenInNewTab}
            variant="outline"
            size="sm"
          >
            <ExternalLink className="h-4 w-4 mr-2" />
            Open in New Tab
          </Button>

          {onClose && (
            <Button
              onClick={onClose}
              variant="ghost"
              size="sm"
              className="ml-auto"
            >
              Close
            </Button>
          )}
        </div>
      </div>

      {/* HTML Content Viewer */}
      <div className="report-iframe-container">
        <iframe
          ref={iframeRef}
          srcDoc={sanitizedHtml}
          title="Vedic Horoscope Report"
          sandbox="allow-same-origin allow-scripts allow-popups allow-popups-to-escape-sandbox"
          className="report-iframe"
        />
      </div>

      <style jsx>{`
        .html-report-viewer-container {
          display: flex;
          flex-direction: column;
          height: 100%;
          width: 100%;
          background: #f5f5f5;
        }

        .toolbar {
          background: white;
          border-bottom: 1px solid #e5e7eb;
          padding: 12px 16px;
          box-shadow: 0 1px 3px rgba(0, 0, 0, 0.1);
        }

        .toolbar-actions {
          display: flex;
          gap: 8px;
          align-items: center;
          flex-wrap: wrap;
        }

        .report-iframe-container {
          flex: 1;
          overflow: hidden;
          position: relative;
          background: white;
        }

        .report-iframe {
          width: 100%;
          height: 100%;
          border: none;
          display: block;
        }

        @media (max-width: 640px) {
          .toolbar {
            padding: 8px 12px;
          }

          .toolbar-actions {
            flex-direction: column;
            width: 100%;
          }

          .toolbar-actions > * {
            width: 100%;
          }
        }
      `}</style>
    </div>
  );
};

export default HtmlReportViewer;
